spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/curso_spring_boot_udemy?useTimezone=true&serverTimezone=UTC
    username: root
    password: ekwa7tmo
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false